cc_library(
    name = "treap",
    hdrs = [
        "treap/adapter.h",
        "treap/treap.h",
        "treap/node.h",
    ],
    srcs = [
        "treap/node.cpp",
    ],
    include_prefix = "algo",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "aho_corasick",
    hdrs = [
        "aho_corasick/aho_corasick.h",
    ],
    include_prefix = "algo",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "segment_tree",
    hdrs = [
        "segment_tree/segment_tree.h",
    ],
    include_prefix = "algo",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "sparse_tree",
    hdrs = [
        "sparse_tree/sparse_tree.h",
    ],
    include_prefix = "algo",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "fenwick_tree",
    hdrs = [
        "fenwick_tree/fenwick_tree.h",
    ],
    include_prefix = "algo",
    visibility = ["//visibility:public"],
)

