cc_library(
    name = "utility",
    srcs = [
        "random.cpp",
    ],
    hdrs = [
        "random.h",
    ],
    include_prefix = "test",
    visibility = ["//visibility:public"],
    deps = [
        "//src/utility",
    ],
)
